#!/bin/sh

#DEBHELPER#

# register to alternatives
update-alternatives \
	--install \
		/usr/bin/x-terminal-emulator \
		x-terminal-emulator \
		/usr/bin/st 50 \
	--slave \
		/usr/share/man/man1/x-terminal-emulator.1.gz \
		x-terminal-emulator.1.gz \
		/usr/share/man/man1/st.1.gz

# register terminfo
tic -s /usr/share/st/st.info

